### PR TITLE
open connection when binlog_checksum is NONE

### PR DESCRIPTION
**Pull request by roopen219**

### CODE REVIEW

**Comment by roopen219** [comment]
@vlasky

**Comment by vlasky** [comment]
@roopen219 please explain why this fix is necessary and what problems are caused by not having it.

**Comment by roopen219** [comment]
@vlasky I am using zongji wrapped within a Readable stream for backpressuring by manually calling `zongji.connection.pause` and `resume`. And when the `binlog_checksum` parmeter is set to NONE, `zongji.connection` has not yet established a connection and any call to `zongi.connection.resume` leads to an internal `cannot call property 'resume' of undefined` exception within `mysql/Connection.js`. And all of this is after waiting on 'ready' event of Zongji.

**Comment by roopen219** [comment]
Example implementation of the stream class

```
class MySQLContSyncStream extends Readable {
  constructor() {
    super({
      objectMode: true,
    });
  }

  _construct(cb) {
    this.zongji = new zongji();
    this.zongji.on('binlog', (event) => {
      let pushMore = true;
      pushMore = this.push(event);
      if (!pushMore) {
        this.zongji.connection.pause();
      }
    });
    zongji.on('ready', () => {
      this.zongji.start();
      cb();
    });
  }

  _read(): void {
    this.zongji.connection.resume();
  }

  _destroy(err, cb) {
    this.zongji.connection.end();
    this.push(null);
    super._destroy(err, cb);
  }
}

export default MySQLContSyncStream;
```

**Comment by vlasky** [comment]
@roopen219 please explain - what is the purpose of this "set timezone" commit? How does it relate to the  binlog_checksum functionality?

https://github.com/vlasky/zongji/pull/1/commits/be4f9dd44642b4b8bb69577e81a7d39e18eda1ab

**Comment by roopen219** [comment]
Ah sorry.. that is unrelated, I was adding timezone functionality for databases not running in UTC. Will create a separate PR for that.

**Comment by vlasky** [comment]
> Ah sorry.. that is unrelated, I was adding timezone functionality for databases not running in UTC. Will create a separate PR for that.

Thanks for the clarification.

**Pull request closed without merging**
